### ISSUE TITLE
STT groq audio buffer needs to be in m4a format 

### ISSUE THREAD

**Issue by bsbarkur** [PeoplePlusAI/sunva-ai#42]
Need this perhaps for streaming transcription as per groq docs. m4a is better for streaming apparently than wav.

```
filename = os.path.dirname(__file__) + "/audio.m4a"

with open(filename, "rb") as file:
    transcription = client.audio.transcriptions.create(
      file=(filename, file.read()),
      model="whisper-large-v3",
      response_format="verbose_json",
    )
```

**Comment by bsbarkur** [comment]
Tracking here `test_stt_transcription_loop` with few tests to compare m4a and wav audio streams.

**Comment by bsbarkur** [comment]
Directly reading audio buffer reduces the latency of processing by skipping file conversion.

Think about how to remove silences - next step.

**Comment by gksoriginals** [comment]
@bsbarkur I added is_silent logic to this branch. Tested and latency is not affected much by adding is_slient. Please test it and revert the commit incase of any issues.
