### ISSUE TITLE
TTS  sentence seperator

### ISSUE THREAD

**Issue by bsbarkur** [PeoplePlusAI/sunva-ai#9]
`const sentences = currentText.split('.');` currently full stop is being used to seperate out the sentences.

What if users type other seperators?

Till this multi- seperator and proper sentence processing and input processing in place. Add instructions for user to end the sentences with a full stop seperator always (just for the demo).

**Comment by gksoriginals** [comment]
@bsbarkur is it possible to deal this in the backend api ?

**Comment by gksoriginals** [comment]
#27 fixed this issue. For now dealing this in frontend. Later will move to backend
